Silex\Provider\DoctrineServiceProvider:
  db.options:
    driver:     pdo_mysql
    host:       {{ db_host }}
    dbname:     {{ db_name }}
    user:       {{ db_user }}
    password:   {{ db_pass }}